# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- ansible.builtin.import_playbook: exporter.yml
- ansible.builtin.import_playbook: grafana.yml
- ansible.builtin.import_playbook: loki.yml
- ansible.builtin.import_playbook: prometheus.yml
