# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: postgres-exporter restart
  hosts: exporter_postgres
  tasks:
    - tosit.tdp.resolve: # noqa name[missing]
        node_name: exporter_postgres
    - name: Restart postgres exporter
      ansible.builtin.import_role:
        name: tosit.tdp_observability.exporter.postgres
        tasks_from: restart
    - ansible.builtin.meta: clear_facts # noqa name[missing]
