# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: node-exporter stop
  hosts: exporter_node
  tasks:
    - tosit.tdp.resolve: # noqa name[missing]
        node_name: exporter_node
    - name: Stop node exporter
      ansible.builtin.import_role:
        name: tosit.tdp_observability.exporter.node
        tasks_from: stop
    - ansible.builtin.meta: clear_facts # noqa name[missing]
